# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4fe2120fd42b22cd72be84fd26d584bc41165ea5229faf75265f556be5acd1166d1990e536899249eb8944ee4023b1a88c9c1a78a1ebe8ca666da5871edd2ea0

test:
  secret_key_base: a89366afa492d6c5b756e4424bf2e1ba40a03e615ffb66f3381a46f6a615b0af0bd275e560496f7a7ea3b7cbb82e0fb22e92cc9be862830354e139528b89df8c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
